name: Build iOS

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-ios.yml"
      - "package/cpp/**"
      - "package/ios/**"
      - "package/*.podspec"
      - "package/example/AppExampleFabric/ios/**"
  pull_request:
    paths:
      - ".github/workflows/build-ios.yml"
      - "package/cpp/**"
      - "package/ios/**"
      - "package/*.podspec"
      - "package/example/AppExampleFabric/ios/**"

jobs:
  build:
    name: Build iOS Example App
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: package/example/AppExampleFabric/ios
    steps:
      - uses: actions/checkout@v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Restore node_modules from cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install node_modules for example/
        run: yarn install --immutable

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v2
        continue-on-error: true

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true
          working-directory: package/example/AppExampleFabric/

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: package/example/ios/AppExampleFabric/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: bundle exec pod install
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build App
        run: "set -o pipefail && xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ GCC_OPTIMIZATION_LEVEL=0 GCC_PRECOMPILE_PREFIX_HEADER=YES ASSETCATALOG_COMPILER_OPTIMIZATION=time DEBUG_INFORMATION_FORMAT=dwarf COMPILER_INDEX_STORE_ENABLE=NO \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace AppExampleFabric.xcworkspace \
          -scheme AppExampleFabric \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
